print("1. Reverse a string")
print("2. Count vowels in string")
print("3. Sum a list numbers")
print("4. Print longest string in list")
print("5. Print Number divisible by 3")
print("6. Return a list of even numbers")
print("7. Remove vowels from string")
print("8. Reverse string from list")
print("9. Print multiplication table")
print("10. Average of numbers")